---
- hosts: switches
  gather_facts: False

  tasks:

  - name: run fos commands
    brocade_fos_command:
      switch_login: admin
      switch_password: password
      switch_address: 10.1.2.3
      command_set:
        # 
        - command: zoneshow

        - command: alishow

        - command: portname

        - command: alicreate "SampleAlias1", "10:23:45:67:76:54:32:10"

        - command: alicreate "SampleAlias2", "10:23:45:67:76:54:32:11"

        - command: zonecreate "SampleZone", "SampleAlias1;SampleAlias2"

        - command: cfgsave
          prompts:
            - question: Do you want to save
              response: "yes"



    register: configout

  - name: print ansible_facts gathered
    debug:
      var: configout
